services:
  postgres:
    image: postgres:16
    container_name: domusvibes-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: domusvibedb
    ports:
      - "5432:5432"
